baseURL = "https://shivsharma07.github.io"
title = "Shiv"
theme = "erblog"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
    author = "Shiv Shankar Sharma"
    badge = "orange"
    quote = "red"
    index_posts_num = 5
    google_search = true
    # logo = "//blog.ertuil.top/avater.png"
    bio = """
    <p> 8.5+ years of experience as backend engineer, experienced in designing, implementing
		and leading software solutions. Cloud technology and DevOps enthusiast.
	</p>
    """
    # copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."


[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

# [[menu.main]]
#     identifier = "zone"
#     name = "Zone"
#     url = "/zone/"
#     weight = 10

[[menu.footer]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

[[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[menu.icon]]
    url = "mailto:shivsharma07@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/shivsharma07"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/shivsharma07"
    name = "twitter"
    weight = 1

